version: '3'
services:
  strapi:
    build: .
    image: strapi-server:latest
    container_name: strapi-server
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      NODE_ENV: production
    ports:
      - "1337:1337"
    volumes:
      # Persist important directories
      - ./.strapi:/opt/server/.strapi
      - ./config:/opt/server/config
      - ./database:/opt/server/database
      - ./public/uploads:/opt/server/public/uploads
      - ./src:/opt/server/src
      - ./types:/opt/server/types
      # Important files
      - ./.env:/opt/server/.env
      - ./package.json:/opt/server/package.json
      - ./package-lock.json:/opt/server/package-lock.json
      - ./tsconfig.json:/opt/server/tsconfig.json